app/user_auth/forms.py
#forms user_auth
from wtforms import StringField,PasswordField,SubmitField,BooleanField
from wtforms.validators import Required,Email,EqualTo
from ..models import User
from wtforms import ValidationError
from flask_wtf import FlaskForm


class RegistrationForm(FlaskForm):
    email = StringField('Your Email Address',validators=[Required(),Email()])
    username = StringField('Enter your username',validators = [Required()])
    password = PasswordField('Password',validators = [Required(), EqualTo('password_confirm',message = 'Passwords must match')])
    password_confirm = PasswordField('Confirm Passwords',validators = [Required()])
    submit = SubmitField('Sign Up')

    def validate_email(self,data_field):
        if User.query.filter_by(email =data_field.data).first():
            raise ValidationError('There is an account with that email')

    def validate_username(self,data_field):
        if User.query.filter_by(username = data_field.data).first():
            raise ValidationError('That username is taken')

class LoginForm(FlaskForm):
    email = StringField('Your Email Address',validators=[Required(),Email()])
    password = PasswordField('Password',validators =[Required()])
    remember = BooleanField('Remember me')
    submit = SubmitField('Sign In')    

app/user_auth/__init__.py
#__init__ user_auth
from flask import Blueprint

user_auth = Blueprint('user_auth',__name__)

from . import views,forms

app/user_auth/views.py
from flask import render_template,redirect,url_for,flash,request
from .. import db
from flask_login import login_user
from ..models import User
from .forms import LoginForm,RegistrationForm
from flask_login import login_user,logout_user,login_required
from . import user_auth


@user_auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))


@user_auth.route('/register',methods = ["GET","POST"])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(email = form.email.data, username = form.username.data,password = form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('user_auth.login'))
        title = "New Account"
    return render_template('user_auth/registration.html',registration_form = form)
    
@user_auth.route('/login',methods=['GET','POST'])
def login():
    login_form = LoginForm()
    if login_form.validate_on_submit():
        user = User.query.filter_by(email = login_form.email.data).first()
        if user is not None and user.verify_password(login_form.password.data):
            login_user(user,login_form.remember.data)
            return redirect(request.args.get('next') or url_for('main.index'))

        flash('Invalid username or Password')

    title = "user login"
    return render_template('user_auth/login.html',login_form = login_form,title=title)    

app/templates/user_auth/login.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<br>
<br>
<br>

<div class="container"> 
    <div class="row">
      <div class= "col-md-2"> </div>
      <div class="col-md-8">
      <!--Flash message -->
      {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
        </div>
      {% endfor %}
    <div class="jumbotron">
      <div class="col-md-7" style="margin-left: 200px;">
      {{wtf.quick_form(login_form)}}
      <p> Don't have an account? <a href="{{url_for('user_auth.register')}}">Sign up here</a></p>
    </div>
     </div>
    </div>
     <div clas="col-md-2"> </div>
    </div>
</div>
{% endblock%}

app/templates/user_auth/registration.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
<div class="row">
<div class="col-md-2"> </div>
<div class="col-md-8">
<div class="jumbotron">
{{wtf.quick_form(registration_form)}}
</div>
</div>
<div class="col-md-2"></div>
</div>
</div>

{% endblock%}