app/admin_auth/forms.py
from flask_wtf import FlaskForm

# inportation of input fields from
from wtforms import StringField, PasswordField, SubmitField, BooleanField, RadioField, TextAreaField

# importation of validators
from wtforms.validators import Required, Email, EqualTo

# custom validator
from wtforms import ValidationError

# import User model
from ..models import User

class RegistrationForm(FlaskForm):
    """
    registration form class for creation of input fields

    """
    username = StringField('Input username', validators=[Required()])
    email = StringField('Input Email Address', validators=[Required(), Email()])
    password = PasswordField('Password',validators=[Required(), EqualTo('password', message='Passwords must match')])
    password_second = PasswordField('Confirm password', validators=[Required()])
    submit = SubmitField('SIGN UP')

    def validate_email(self, data_field):
        """
        Method to checking if email used matches existing emails

        """
        if User.query.filter_by(email=data_field.data).first():
            raise ValidationError('Email matches existing account')

    def validate_username(self, data_field):
        """
        checking if username keyed in matches existing usernames

        """
        if User.query.filter_by(username=data_field.data).first():
            raise ValidationError('Username is already Taken, try another one')

class LoginForm(FlaskForm):
    """
    login form class to create login form
    """
    email = StringField('Email Address Here', validators=[Required(), Email()])
    password = PasswordField('Password', validators=[Required()])
    remember = BooleanField('Remember me') # render checkbox to remember password details
    submit = SubmitField('Log In')

app/admin_auth/__init__.py
from flask import Blueprint

# creating a blueprint instance
admin_auth = Blueprint('admin_auth', __name__)

from . import views, forms

app/admin_auth/views.py
from flask import render_template, url_for, redirect, request, flash
from . import admin_auth
from flask_login import login_user, login_required, logout_user
# imoort user model
from ..models import Admin
from .forms import RegistrationForm, LoginForm
from .. import db

@admin_auth.route('/loginadmin', methods=['GET', 'POST'])
def login():
    """
    login function to render template file
    :return:
    """
    login_form=LoginForm() # instance of Login form passed into login template
    if login_form.validate_on_submit():
        """
        checking form validation
        """
        admin=Admin.query.filter_by(email = login_form.email.data).first()
        """
        searching for user in database with email received from form
        """
        if admin is not None and admin.verify_password(login_form.password.data):
            login_user(admin, login_form.remember.data)
            return redirect(request.args.get('next') or url_for('admin_auth.admindashboard'))

        flash('Invalid username or Password')

    title = "ADMIN DASHBOARD"
    return render_template('admin_auth/adminlogin.html', login_form=login_form, title=title)


@admin_auth.route('/registeradmin', methods=['GET','POST'])
def register():
    """
    function to render registration form
    :return:
    """
    form = RegistrationForm()
    if form.validate_on_submit():

        admin = Admin(username=form.username.data, email=form.email.data)
        admin.set_password(form.password.data)
        db.session.add(admin)
        db.session.commit()

        title = "Welcome Admin"
        return redirect(url_for('admin_auth.login'))
    return render_template('admin_auth/adminregister.html', registration_form=form)


# logout route to logout user from application
@admin_auth.route('/logoutadmin')
@login_required
def logout():
    """
    function to logout user
    :return:
    """
    logout_user()
    return redirect(url_for("main.index"))

app/templates/admin_auth/adminlogin.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
    <div class="row">
      <div class= "col-md-2"> </div>
      <div class="col-md-8">
      <!--Flash message -->
      {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
        </div>
      {% endfor %}
      <!-- Login form -->
      <div class="jumbotron">
      {{wtf.quick_form(login_form)}}

      <p> Don't have an account? <a href="{{url_for('admin_auth.register')}}">Sign up here</a></p>
    </div>
    </div>
     <div clas="col-md-2"> </div>
    </div>
</div>

{% endblock%}

app/templates/admin_auth/adminregister.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf%}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2">

        </div>
        <div class="col-md-8">

            <!-- rendering the registration form using wtf.quickform-->
            <div class="jumbotron">
            {{wtf.quick_form(registration_form)}}
            </div>
        <div class="col-md-2">

        </div>
    </div>
</div>

{% endblock %}